services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: newshub_db
      MYSQL_USER: newshub_admin
      MYSQL_PASSWORD: newshub_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: pypy manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: newshub_db
      DJANGO_DB_USER: newshub_admin
      DJANGO_DB_PASSWORD: newshub_pass
      DJANGO_DB_PORT: "3306"

volumes:
  db_data:
