services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: newshub_db
      MYSQL_USER: newshub_admin
      MYSQL_PASSWORD: newshub_pass
      MYSQL_ROOT_PASSWORD: root_pass
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: newshub_db
      DB_USER: newshub_admin
      DB_PASSWORD: newshub_pass
      DB_PORT: 3306
    ports:
      - "8000:8000"
